name: Documentation

on:
  push:
    branches: [ 'master' ]
  pull_request:

  workflow_dispatch:

# Compile the docs and deploy to GitHub pages
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks out the repository
      - uses: actions/checkout@v3
        with:
          ref: 'master'

      - name: Install pandoc
        run: sudo apt-get install -y pandoc

      # Upgrade pip
      - name: Upgrade pip
        run: |
          # install pip=>20.1 to use "pip cache dir"
          python3 -m pip install --upgrade pip

      # Cache dependencies
      - name: Get pip cache dir
        id: pip-cache
        run: echo "dir=$(pip cache dir)" >> "$GITHUB_OUTPUT"

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.pip-cache.outputs.dir }}
          key: ${{ runner.os }}-pip-${{ hashFiles('**/extras/docs.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # Install base dependencies
      - name: Install dependencies
        run: python3 -m pip install -r requirements.txt

      # Install sphinx
      - name: Install dependencies
        run: python3 -m pip install -r ./extras/docs.txt

      # Make docs
      - name: Build docs
        run: cd docs && make html
        
      # Deploy
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build/html/
